import Head from 'next/head'

import Header from '@/components/Header'
import { useState } from 'react'

import {Country} from "../types/Country"
import {IHome} from "../types/types"
import { count } from 'console'


export default function Home({data}:IHome) {


  const [countries, setCountries] = useState(data)
  console.log(countries);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
      </main>
    </>
  )
}

export const getStaticProps = async() => {
  let countries;
  const API_URL = "https://restcountries.com/v3.1/all"
  const res = await fetch(API_URL)
  const data = await res.json() as Country[]
  countries = data.map(country => {
    return{
      flag: country.flags.png,
      name: country.name.common,
      population: country.population,
      region: country.region,
      capital: country.capital ? country.capital[0] : null
    }
  })

  return{
    props:{
      data: countries,
    }
  }
}
