import Head from 'next/head'
import { ChangeEvent, useContext, useState } from 'react'

import Header from '@/components/Header'
import CountryList from '@/components/CountryList'

import {Country} from "../types/Country"
import {IHome} from "../types/types"

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSearch } from '@fortawesome/free-solid-svg-icons'
import { ThemeContext } from '@/context/ThemeContext'


export default function Home({data}:IHome) {

  const [countries, setCountries] = useState(data)
  const [inputValue, setInputValue] = useState<string>("")
  const [selectValue, setSelectValue] = useState<string>("")

  const themeColor = useContext(ThemeContext)
  const [theme, setTheme] = useState(themeColor)

  const handleInput = (e: ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value)
  }

  const handleSelect = (e: ChangeEvent<HTMLSelectElement>) => {
    setSelectValue(e.target.value)
  }

  const handleTheme = () => {
    const themeChange = theme == "light" ? "dark" : "light";
    setTheme(themeChange)
  }

  console.log(theme);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeContext.Provider value={theme}>
      <main className={`main-${theme}`}>
        <Header handleTheme={handleTheme}/>
        <div className={`filter`}>
          <div className={`input input-${theme}`}><FontAwesomeIcon className={`icon icon-${theme}`} icon={faSearch} /><input type="text" className={`inputForm-${theme}`} placeholder='Search for a country' value={inputValue} onChange={handleInput} /></div>
          <select className={`select-${theme}`} value={selectValue} onChange={handleSelect}>
            <option value="">Default</option>
            <option value="Africa">Africa</option>
            <option value="America">America</option>
            <option value="Asia">Asia</option>
            <option value="Europe">Europe</option>
            <option value="Oceania">Oceania</option>
          </select>
        </div>
        <CountryList countries={countries.filter(country => country.name.toLocaleLowerCase().includes(inputValue.toLocaleLowerCase()) && country.region.toLocaleLowerCase().includes(selectValue.toLocaleLowerCase()))}/>
      </main>
      </ThemeContext.Provider>
    </>
  )
}

export const getStaticProps = async() => {
  let countries
  const API_URL = "https://restcountries.com/v3.1/all"
  const res = await fetch(API_URL)
  const data = await res.json() as Country[]
  countries = data.map(country => {
    return{
      flag: country.flags.png,
      name: country.name.common,
      population: country.population,
      region: country.region,
      capital: country.capital ? country.capital[0] : null
    }
  })

  return{
    props:{
      data: countries,
    }
  }
}
